swiftmailer:
    # url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    username: '%env(MAILER_USER%'
    password: '%env(MAILER_PASSWORD)%'
    host: '%env(MAILER_HOST)%'
    port: '%env(MAILER_PORT)%'
    encryption: 'tls'
    sender_address: '%env(MAILER_FROM)%'
